#!/usr/bin/env bash
#
# Linux/NVIDIA bootstrap for the YAM + TiPToP simulation stack.
#
# This follows the TiPToP docs for TiPToP/cuRobo/cuTAMP and the TiPToP M2T2
# fork, then applies the repo-local YAM bridge patches.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/yam_stack_common.sh
source "$SCRIPT_DIR/yam_stack_common.sh"
yam_stack_load_env

TIPTOP_REPO="${TIPTOP_REPO:-https://github.com/tiptop-robot/tiptop.git}"
M2T2_REPO="${M2T2_REPO:-https://github.com/williamshen-nz/M2T2.git}"
SKIP_M2T2_WEIGHTS=0
SKIP_MUJOCO=0
REGENERATE_ASSETS=0

usage() {
  cat <<'EOF'
Usage: scripts/bootstrap_yam_stack.sh [options]

Options:
  --skip-m2t2-weights   Do not download M2T2 weights.
  --skip-mujoco         Do not create/install the MuJoCo Playground venv.
  --regenerate-assets   Regenerate YAM cuRobo assets even if yam.yml exists.
  -h, --help            Show this help.

Environment:
  YAM_LOCAL             Machine-local cache/env root. Defaults to /opt/yam-local
                        when writable/root, otherwise ~/.cache/yam-mjx.
  TORCH_CUDA_ARCH_LIST  CUDA arch for M2T2 pointnet2_ops. Defaults to 8.9.

The script is Linux/NVIDIA-oriented. It intentionally keeps heavy envs outside
the repo and symlinks them in before installing, so env paths stay stable.
EOF
}

while (($#)); do
  case "$1" in
    --skip-m2t2-weights) SKIP_M2T2_WEIGHTS=1 ;;
    --skip-mujoco) SKIP_MUJOCO=1 ;;
    --regenerate-assets) REGENERATE_ASSETS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) yam_stack_die "Unknown option: $1" ;;
  esac
  shift
done

require_linux() {
  [[ "$(uname -s)" == "Linux" ]] || yam_stack_die "This bootstrap currently supports Linux only."
  command -v git >/dev/null || yam_stack_die "git is required."
}

ensure_dir() {
  mkdir -p "$@"
}

ensure_symlink_dir() {
  local link_path="$1"
  local target_path="$2"
  ensure_dir "$target_path"
  ensure_dir "$(dirname "$link_path")"

  if [[ -L "$link_path" ]]; then
    if [[ "$(readlink "$link_path")" != "$target_path" ]]; then
      rm "$link_path"
      ln -s "$target_path" "$link_path"
    fi
    return
  fi

  if [[ -e "$link_path" ]]; then
    yam_stack_die "$link_path already exists and is not a symlink. Move it aside, then rerun."
  fi

  ln -s "$target_path" "$link_path"
}

clone_if_missing() {
  local repo_url="$1"
  local dest="$2"
  if [[ -d "$dest/.git" ]]; then
    yam_stack_log "Found existing checkout: $dest"
    return
  fi
  if [[ -e "$dest" ]]; then
    yam_stack_die "$dest exists but is not a git checkout."
  fi
  yam_stack_log "Cloning $repo_url -> $dest"
  git clone "$repo_url" "$dest"
}

ensure_pixi() {
  ensure_dir "$PIXI_HOME" "$PIXI_CACHE_DIR"
  if command -v pixi >/dev/null; then
    pixi --version
    return
  fi

  yam_stack_log "Installing pixi into PIXI_HOME=$PIXI_HOME"
  curl -fsSL https://pixi.sh/install.sh | bash
  export PATH="$PIXI_HOME/bin:$PATH"
  command -v pixi >/dev/null || yam_stack_die "pixi install completed but pixi is still not on PATH."
  pixi --version
}

ensure_uv() {
  ensure_dir "$UV_CACHE_DIR"
  if command -v uv >/dev/null; then
    uv --version
    return
  fi

  yam_stack_log "Installing uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  command -v uv >/dev/null || yam_stack_die "uv install completed but uv is still not on PATH."
  uv --version
}

write_env_file() {
  ensure_dir "$YAM_LOCAL"
  local env_file="$YAM_LOCAL/yam_env.sh"
  yam_stack_log "Writing $env_file"
  cat > "$env_file" <<EOF
# Generated by YAM-MJX/scripts/bootstrap_yam_stack.sh
export YAM_ROOT="$YAM_ROOT"
export YAM_LOCAL="$YAM_LOCAL"
export YAM_EXTERNAL_DIR="\$YAM_ROOT/external"
export YAM_TIPTOP_DIR="\$YAM_EXTERNAL_DIR/tiptop"
export YAM_M2T2_DIR="\$YAM_EXTERNAL_DIR/M2T2"
export YAM_PLAYGROUND_DIR="\$YAM_ROOT/mujoco_playground"
export YAM_MUJOCO_VENV="$YAM_MUJOCO_VENV"

export PIXI_HOME="$PIXI_HOME"
export PIXI_CACHE_DIR="$PIXI_CACHE_DIR"
export UV_CACHE_DIR="$UV_CACHE_DIR"
export UV_LINK_MODE="$UV_LINK_MODE"
export PATH="\$PIXI_HOME/bin:\$HOME/.local/bin:\$HOME/.pixi/bin:\$PATH"

export TIPTOP_PACKAGE_DIR="\$YAM_TIPTOP_DIR"
export YAM_TIPTOP_ASSETS_DIR="\$YAM_PLAYGROUND_DIR/tiptop_yam_assets"

export MUJOCO_GL=egl
export PYOPENGL_PLATFORM=egl
export EGL_PLATFORM=surfaceless
if [ -f /usr/share/glvnd/egl_vendor.d/10_nvidia.json ]; then
  export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
fi
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:\${LD_LIBRARY_PATH:-}"

export TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST:-8.9}"
export MAX_JOBS="${MAX_JOBS:-2}"
EOF
}

install_tiptop_stack() {
  clone_if_missing "$TIPTOP_REPO" "$YAM_TIPTOP_DIR"
  [[ -f "$YAM_TIPTOP_DIR/pixi.toml" ]] || yam_stack_die "No pixi.toml in $YAM_TIPTOP_DIR"
  ensure_symlink_dir "$YAM_TIPTOP_DIR/.pixi" "$YAM_LOCAL/pixi-envs/tiptop"

  yam_stack_log "Installing TiPToP dependencies"
  (
    cd "$YAM_TIPTOP_DIR"
    pixi install
  )

  yam_stack_log "Checking TiPToP planner setup"
  if (
    cd "$YAM_TIPTOP_DIR"
    pixi run python - <<'PY' >/dev/null 2>&1
from tiptop.utils import check_cutamp_version
check_cutamp_version()
import curobo
PY
  ); then
    yam_stack_log "TiPToP planner imports are already healthy"
  else
    (
      cd "$YAM_TIPTOP_DIR"
      pixi run setup-planners
      pixi run tiptop-run -h >/dev/null
    )
  fi
}

install_yam_bridge() {
  yam_stack_log "Preparing repo-local YAM assets"
  ensure_symlink_dir "$YAM_PLAYGROUND_DIR/mujoco_playground/external_deps" "$YAM_LOCAL/external_deps"

  local asset_args=()
  if [[ "$REGENERATE_ASSETS" == "1" ]]; then
    asset_args+=(--regenerate-assets)
  fi

  (
    cd "$YAM_TIPTOP_DIR"
    pixi run python "$YAM_PLAYGROUND_DIR/scripts/install_tiptop_yam_bridge.py" \
      --tiptop-root "$YAM_TIPTOP_DIR" \
      "${asset_args[@]}"
  )
}

install_m2t2_stack() {
  clone_if_missing "$M2T2_REPO" "$YAM_M2T2_DIR"
  [[ -f "$YAM_M2T2_DIR/pixi.toml" ]] || yam_stack_die "No pixi.toml in $YAM_M2T2_DIR. Expected TiPToP's M2T2 fork: $M2T2_REPO"
  ensure_symlink_dir "$YAM_M2T2_DIR/.pixi" "$YAM_LOCAL/pixi-envs/M2T2"

  yam_stack_log "Checking M2T2 setup"
  if (
    cd "$YAM_M2T2_DIR"
    pixi run python - <<'PY' >/dev/null 2>&1
from pointnet2_ops import _ext
import m2t2
PY
  ); then
    yam_stack_log "M2T2 imports are already healthy"
  else
    (
      cd "$YAM_M2T2_DIR"
      pixi run setup
      pixi run python - <<'PY'
from pointnet2_ops import _ext
import m2t2
print("M2T2 setup ok")
PY
    )
  fi

  if [[ "$SKIP_M2T2_WEIGHTS" == "1" ]]; then
    yam_stack_warn "Skipping M2T2 weights download."
    return
  fi

  if [[ -f "$YAM_M2T2_DIR/weights/m2t2.pth" ]]; then
    yam_stack_log "Found M2T2 weights"
    (
      cd "$YAM_M2T2_DIR"
      if command -v md5sum >/dev/null; then
        echo '1f8354df8e7f7be10c5edc05cba937a4  weights/m2t2.pth' | md5sum -c - || true
      fi
    )
  else
    yam_stack_log "Downloading M2T2 weights via TiPToP M2T2 task"
    (
      cd "$YAM_M2T2_DIR"
      pixi run download-weights
    ) || yam_stack_warn "M2T2 weight download failed. If this is a Hugging Face/Git LFS issue, install git-lfs or copy m2t2.pth into $YAM_M2T2_DIR/weights/"
  fi
}

install_mujoco_playground() {
  if [[ "$SKIP_MUJOCO" == "1" ]]; then
    yam_stack_warn "Skipping MuJoCo Playground venv."
    return
  fi

  ensure_uv
  ensure_symlink_dir "$YAM_PLAYGROUND_DIR/.venv" "$YAM_MUJOCO_VENV"
  yam_stack_log "Installing MuJoCo Playground venv"
  (
    cd "$YAM_PLAYGROUND_DIR"
    if [[ ! -x "$YAM_MUJOCO_VENV/bin/python" ]]; then
      uv venv "$YAM_MUJOCO_VENV" --python 3.12
    fi
    # shellcheck disable=SC1091
    source "$YAM_MUJOCO_VENV/bin/activate"
    uv pip install -e .
  )

  if ! ldconfig -p 2>/dev/null | grep -q 'libEGL.so.1'; then
    yam_stack_warn "libEGL.so.1 was not found. On Ubuntu, install it with: apt-get update && apt-get install -y libegl1"
  fi
}

print_next_steps() {
  cat <<EOF

YAM stack bootstrap finished.

Use this in new terminals:
  source "$YAM_LOCAL/yam_env.sh"

Terminal 1:
  scripts/start_m2t2_server.sh

Terminal 2:
  scripts/make_tiptop_h5.sh
  export GOOGLE_API_KEY="your-key"
  scripts/run_tiptop_yam.sh
  scripts/render_tiptop_latest.sh
EOF
}

main() {
  require_linux
  ensure_dir "$YAM_LOCAL" "$YAM_EXTERNAL_DIR" "$YAM_LOCAL/pixi-envs" "$YAM_LOCAL/venvs"
  write_env_file
  ensure_pixi
  install_tiptop_stack
  install_yam_bridge
  install_m2t2_stack
  install_mujoco_playground
  print_next_steps
}

main "$@"
